### ISSUE TITLE
How to use this .so package in Android?

### ISSUE THREAD

**Issue by JimssM** [tun2proxy/tun2proxy#124]
I run it and got error:
```
2024-06-18 12:36:35.174 24166-27358 com.mjhelper            pid-24166                            
E  No implementation found for int com.services.MyVpnService.tun2proxy_with_fd_run(java.lang.String, int, boolean, int, int, int) (tried Java_com_services_MyVpnService_tun2proxy_1with_1fd_1run and Java_com_services_MyVpnService_tun2proxy_1with_1fd_1run__Ljava_lang_String_2IZIII)
2024-06-18 12:36:35.174 24166-27358 AndroidRuntime          pid-24166                            
E  FATAL EXCEPTION: Thread-2 (Ask Gemini)
       Process: com.mjhelper, PID: 24166
       java.lang.UnsatisfiedLinkError: No implementation found for int com.services.MyVpnService.tun2proxy_with_fd_run(java.lang.String, int, boolean, int, int, int) (tried Java_com_services_MyVpnService_tun2proxy_1with_1fd_1run and Java_com_services_MyVpnService_tun2proxy_1with_1fd_1run__Ljava_lang_String_2IZIII)
       at com.services.MyVpnService.tun2proxy_with_fd_run(Native Method)
       at com.services.MyVpnService.startVpnService(MyVpnService.java:87)
       at com.services.MyVpnService$1.run(MyVpnService.java:75)
       at java.lang.Thread.run(Thread.java:764)
```
I can load library,but can't use native function. this is my define:
```
    public native int tun2proxy_with_fd_run(String proxyUrl, int tunFd, boolean packetInformation, int tunMtu, int dnsStrategy, int verbosity);
    public native int tun2proxy_with_fd_stop();
```

**Comment by JimssM** [comment]
now I set it to proper file:
package com.github.shadowsocks.bg;

public class Tun2proxy {

    public native int run(String proxyUrl, int tunFd, boolean packetInformation, int tunMtu, int dnsStrategy, int verbosity);
//    public native int run(int tunFd);
    public native int stop();
    static{
        System.loadLibrary("tun2proxy");

    }

}

and run function steal does'nt work

**Comment by JimssM** [comment]
![image](https://github.com/tun2proxy/tun2proxy/assets/127835699/aff82f08-4675-4474-a8d7-6335780a5ba4)
more running error information

**Comment by JimssM** [comment]
E  Error during sending EventType: TYPE_WINDOW_CONTENT_CHANGED; EventTime: 12587073; PackageName: android; MovementGranularity: 0; Action: 0; ContentChangeTypes: [CONTENT_CHANGE_TYPE_SUBTREE]; WindowChangeTypes: [] [ ClassName: android.widget.FrameLayout; Text: []; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: true; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0 to android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@ec15a05 (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(Binder.java:1127)
                                                                                                    	at android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy.onAccessibilityEvent(IAccessibilityServiceClient.java:228)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.notifyAccessibilityEventInternal(AbstractAccessibilityServiceConnection.java:1090)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.access$000(AbstractAccessibilityServiceConnection.java:74)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection$1.handleMessage(AbstractAccessibilityServiceConnection.java:262)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at com.android.server.SystemServer.run(SystemServer.java:468)
                                                                                                    	at com.android.server.SystemServer.main(SystemServer.java:299)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
2024-06-18 13:27:48.085  1575-3025  EGL_adreno              system_server                        D  eglCreateContext: 0x7fff68ae1d40: maj 3 min 1 rcv 4
2024-06-18 13:27:48.085  1575-1575  AbstractAc...Connection system_server                        E  Error during sending EventType: TYPE_WINDOW_CONTENT_CHANGED; EventTime: 12587074; PackageName: android; MovementGranularity: 0; Action: 0; ContentChangeTypes: [CONTENT_CHANGE_TYPE_SUBTREE]; WindowChangeTypes: [] [ ClassName: android.widget.FrameLayout; Text: []; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: true; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0 to android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@ec15a05 (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(Binder.java:1127)
                                                                                                    	at android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy.onAccessibilityEvent(IAccessibilityServiceClient.java:228)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.notifyAccessibilityEventInternal(AbstractAccessibilityServiceConnection.java:1090)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.access$000(AbstractAccessibilityServiceConnection.java:74)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection$1.handleMessage(AbstractAccessibilityServiceConnection.java:262)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at com.android.server.SystemServer.run(SystemServer.java:468)
                                                                                                    	at com.android.server.SystemServer.main(SystemServer.java:299)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)
2024-06-18 13:27:48.085  1575-1575  AbstractAc...Connection system_server                        E  Error during sending EventType: TYPE_WINDOW_STATE_CHANGED; EventTime: 12587074; PackageName: android; MovementGranularity: 0; Action: 0; ContentChangeTypes: []; WindowChangeTypes: [] [ ClassName: com.android.server.am.AppErrorDialog; Text: [MJHelper屡次停止运行, 应用信息, 关闭应用]; ContentDescription: null; ItemCount: -1; CurrentItemIndex: -1; Enabled: true; Password: false; Checked: false; FullScreen: false; Scrollable: false; BeforeText: null; FromIndex: -1; ToIndex: -1; ScrollX: -1; ScrollY: -1; MaxScrollX: -1; MaxScrollY: -1; AddedCount: -1; RemovedCount: -1; ParcelableData: null ]; recordCount: 0 to android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy@ec15a05 (Ask Gemini)
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(Binder.java:1127)
                                                                                                    	at android.accessibilityservice.IAccessibilityServiceClient$Stub$Proxy.onAccessibilityEvent(IAccessibilityServiceClient.java:228)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.notifyAccessibilityEventInternal(AbstractAccessibilityServiceConnection.java:1090)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection.access$000(AbstractAccessibilityServiceConnection.java:74)
                                                                                                    	at com.android.server.accessibility.AbstractAccessibilityServiceConnection$1.handleMessage(AbstractAccessibilityServiceConnection.java:262)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at com.android.server.SystemServer.run(SystemServer.java:468)
                                                                                                    	at com.android.server.SystemServer.main(SystemServer.java:299)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:840)

**Comment by ssrlive** [comment]
You'd better create a C file from Android Studio [link](https://gist.github.com/okamayana/79c98545eb99c4877979)

and then call `tun2proxy_with_fd_run` from your function.

**Comment by JimssM** [comment]
Thank you

**Comment by ssrlive** [comment]
[wiki](https://github.com/tun2proxy/tun2proxy/wiki/Integrate-to-Android-platform)
